// Downloads the Google Fonts used by the site and rewrites them to be self-hosted,
// so typography never depends on fonts.gstatic.com (which this network resets intermittently).
import { mkdir, writeFile } from 'node:fs/promises';

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,400;12..96,600;12..96,700;12..96,800&family=Hanken+Grotesk:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500;700&display=swap';

// pretend to be a modern Chrome so Google returns compact woff2 files
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';

const OUT = new URL('./src/fonts/', import.meta.url);
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function withRetry(fn, label, tries = 6) {
  let last;
  for (let i = 0; i < tries; i++) {
    try {
      return await fn();
    } catch (e) {
      last = e;
      process.stdout.write(`  retry ${i + 1}/${tries} for ${label} (${e.message})\n`);
      await sleep(700 + i * 500);
    }
  }
  throw last;
}

async function main() {
  await mkdir(OUT, { recursive: true });

  const css = await withRetry(async () => {
    const res = await fetch(CSS_URL, { headers: { 'User-Agent': UA } });
    if (!res.ok) throw new Error('css ' + res.status);
    return res.text();
  }, 'css');

  // split into @font-face blocks
  const blocks = css.split('@font-face').filter((b) => b.includes('url('));
  let out = '/* self-hosted Google Fonts — generated by fetch-fonts.mjs */\n';
  const counters = {};
  let n = 0;

  for (const b of blocks) {
    const fam = (b.match(/font-family:\s*'([^']+)'/) || [])[1] || 'font';
    const weight = (b.match(/font-weight:\s*([^;]+);/) || [])[1]?.trim() || '400';
    const style = (b.match(/font-style:\s*([^;]+);/) || [])[1]?.trim() || 'normal';
    const url = (b.match(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2)\)/) || [])[1];
    const range = (b.match(/unicode-range:\s*([^;]+);/) || [])[1]?.trim() || '';
    if (!url) continue;

    const slug = fam.toLowerCase().replace(/[^a-z0-9]+/g, '-');
    counters[slug] = (counters[slug] || 0) + 1;
    const file = `${slug}-${weight}-${style}-${counters[slug]}.woff2`;

    const buf = await withRetry(async () => {
      const r = await fetch(url, { headers: { 'User-Agent': UA } });
      if (!r.ok) throw new Error('font ' + r.status);
      return Buffer.from(await r.arrayBuffer());
    }, file);
    await writeFile(new URL(file, OUT), buf);
    n++;
    process.stdout.write(`  ✓ ${file} (${(buf.length / 1024).toFixed(1)}kB)\n`);

    out +=
      `@font-face{font-family:'${fam}';font-style:${style};font-weight:${weight};` +
      `font-display:swap;src:url('./${file}') format('woff2');` +
      (range ? `unicode-range:${range};` : '') +
      '}\n';
  }

  await writeFile(new URL('./fonts.css', OUT), out);
  console.log(`\nDone — ${n} font files saved to src/fonts/, fonts.css written.`);
}

main().catch((e) => {
  console.error('fetch-fonts failed:', e.message);
  process.exit(1);
});
